CREATE TABLE Pais(
PaisID INT NOT NULL IDENTITY(1,1),
Nome VARCHAR(50) NOT NULL,
Abreviacao CHAR(20) NOT NULL,
DataInsert DATETIME NULL DEFAULT GETDATE(),
CONSTRAINT PK_Pais PRIMARY KEY (PaisID)
)
GO
 
 

 SET IDENTITY_INSERT Pais ON
 INSERT INTO Pais (PaisID, Nome, Abreviacao)
	SELECT
	PaisID,
	Nome,
	Abreviacao
	FROM [RAWDATA-Pais]
	ORDER BY PaisID
SET IDENTITY_INSERT Pais OFF




	SELECT * FROM Pais
